package com.example.rungps.tracking

data class TrackingUiState(
    val isRecording: Boolean = false,
    val startedAtMs: Long? = null,
    val elapsedMs: Long = 0L,
    val distanceM: Double = 0.0,
    val steps: Long = 0L,
    val lastLat: Double? = null,
    val lastLon: Double? = null,
    val lastFinishedRunId: Long? = null,
    val lastFinishedAtMs: Long? = null,
    val planType: String? = null,
    val segmentLabel: String? = null,
    val segmentIndex: Int? = null,
    val segmentCount: Int? = null,
    val segmentElapsedMs: Long? = null,
    val segmentRemainingMs: Long? = null,
    val segmentDistanceM: Double? = null,
    val segmentRemainingM: Double? = null,
    val workoutFinished: Boolean? = null,
    val isAutoPaused: Boolean = false,
    val isPaused: Boolean = false,
    val currentSplitElapsedMs: Long = 0L,
    val targetPaceSecPerKm: Int? = null,
    val goalDistanceM: Double? = null,
    val goalTimeMs: Long? = null,
    val splitCount: Int = 0,
    val lastSplitMs: Long? = null,
    val lapCount: Int = 0,
    val lastLapMs: Long? = null,
    val hrBpm: Int? = null,
    val hasGpsFix: Boolean = false,
)
